name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./RentalService/pom.xml
          mvn clean package -f ./ReviewService/pom.xml
          mvn clean package -f ./BookService/pom.xml
          mvn clean package -f ./PointService/pom.xml
          mvn clean package -f ./UserService/pom.xml

      - name: Docker Build and push for RentalService
        uses: docker/build-push-action@v4
        with:
          context: ./RentalService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/rentalservice:latest
            ghcr.io/${{ github.repository }}/rentalservice:${{ github.ref_name }}
            
      - name: Docker Build and push for ReviewService
        uses: docker/build-push-action@v4
        with:
          context: ./ReviewService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reviewservice:latest
            ghcr.io/${{ github.repository }}/reviewservice:${{ github.ref_name }}
            
      - name: Docker Build and push for BookService
        uses: docker/build-push-action@v4
        with:
          context: ./BookService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bookservice:latest
            ghcr.io/${{ github.repository }}/bookservice:${{ github.ref_name }}
            
      - name: Docker Build and push for PointService
        uses: docker/build-push-action@v4
        with:
          context: ./PointService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pointservice:latest
            ghcr.io/${{ github.repository }}/pointservice:${{ github.ref_name }}
            
      - name: Docker Build and push for UserService
        uses: docker/build-push-action@v4
        with:
          context: ./UserService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/userservice:latest
            ghcr.io/${{ github.repository }}/userservice:${{ github.ref_name }}
            
