server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: RentalService
          uri: http://localhost:8082
          predicates:
            - Path=/rentalSystems/**, 
        - id: ReviewService
          uri: http://localhost:8083
          predicates:
            - Path=/reviewSystems/**, 
        - id: BookService
          uri: http://localhost:8084
          predicates:
            - Path=/bookSystems/**, 
        - id: PointService
          uri: http://localhost:8085
          predicates:
            - Path=/undefined/**, 
        - id: UserService
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: RentalService
          uri: http://rentalService:8080
          predicates:
            - Path=/rentalSystems/**, 
        - id: ReviewService
          uri: http://reviewService:8080
          predicates:
            - Path=/reviewSystems/**, 
        - id: BookService
          uri: http://bookService:8080
          predicates:
            - Path=/bookSystems/**, 
        - id: PointService
          uri: http://pointService:8080
          predicates:
            - Path=/undefined/**, 
        - id: UserService
          uri: http://userService:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
